cask_args appdir: '/Applications'

brew 'atuin'
brew 'cloudflared'
brew 'imagemagick'
brew 'postgresql@17'
brew 'redis'
brew 'ruby-build'
brew 'spaceman-diff'
brew 'wget'
brew 'yt-dlp'
brew 'lla'
brew 'zsh-autosuggestions'
brew 'vim'
brew 'zoxide'

cask 'ghostty'
cask 'notion-calendar'
cask 'notion'
cask 'qlvideo'
cask 'raycast'
cask 'windsurf'
cask 'visual-studio-code'
cask 'vlc'
cask 'zed'
cask 'slack'
cask 'thebrowsercompany-dia'
cask 'macs-fan-control'